# Internal deployment workflow (sanitized for private repo)
name: Deploy to Azure

# Run only when manually triggered
on:
  workflow_dispatch:
  # Automated triggers removed
name: Deploy to Azure

# Run only when manually triggered
on:
  workflow_dispatch:
  # Automated triggers removed

# Keeping minimal permissions needed
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # Simplified environment variables - keeping only the essential ones
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      # Essential Azure AI settings
      AZURE_AI_AGENT_NAME: ${{ vars.AZURE_AI_AGENT_NAME }}
      AZURE_AI_AGENT_MODEL_NAME: ${{ vars.AZURE_AI_AGENT_MODEL_NAME }}
      AZURE_AI_AGENT_MODEL_FORMAT: ${{ vars.AZURE_AI_AGENT_MODEL_FORMAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install azd
        uses: Azure/setup-azd@v2
        
      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      # Single deployment step instead of separate provision/deploy
      - name: Deploy to Azure
        run: azd up --no-prompt
        env:
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}
